import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import LogoutButton from './logout-button'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()
  return (
    <html lang="en">
      <body>
      
        <main className="min-h-screen bg-blue-400 flex flex-col items-center">
        <div className="flex border-b py-3 text-sm text-neutral-100">
        <span className="ml-auto">
          {user ? (
            <span className="flex gap-4">
              Hey, {user.email}! <span className="border-r"></span>{' '}
              <LogoutButton />
            </span>
          ) : (
            <span className="text-neutral-100 hover:underline">
              Welcome to Spill the bill
            </span>
          )}
        </span>
      </div>
          {children}
        </main>
      </body>
    </html>
  )
}
